version: '3.0'

services:
    db:
      image: postgres:10
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: deSCubra
      volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - 5432:5432
    app:
      build: .
      links:
        - db
      ports:
        - 3000:3000
