CREATE TABLE PERCURSO (
	NOME VARCHAR(60) NOT NULL,
	DESCRICAO TEXT,
	IMAGEM VARCHAR(40),
	CONSTRAINT PERCURSO_PK PRIMARY KEY (NOME)
);

CREATE TABLE EXPLORADOR (
	EMAIL VARCHAR(60) NOT NULL,
	NOME VARCHAR(60) NOT NULL,
	CONSTRAINT EXPLORADOR_PK PRIMARY KEY (EMAIL)
);

CREATE TABLE STATUS (
	PERCURSO VARCHAR(60) NOT NULL,
	EXPLORADOR VARCHAR(60) NOT NULL,
	PARADAATUAL INT,
	CONSTRAINT STATUS_PK PRIMARY KEY (PERCURSO, EXPLORADOR),
	CONSTRAINT STATUS_FK1 FOREIGN KEY (PERCURSO) REFERENCES PERCURSO(NOME),
	CONSTRAINT STATUS_FK2 FOREIGN KEY (EXPLORADOR) REFERENCES EXPLORADOR(EMAIL)
);

CREATE TABLE PARADA (
	PERCURSO VARCHAR(60) NOT NULL,
	CODIGO INT NOT NULL,
	NOME TEXT NOT NULL,
	DESCRICAO TEXT NOT NULL,
	PERGUNTA TEXT NOT NULL,
	RESPOSTA TEXT NOT NULL,
	IMAGEM VARCHAR(40),
	CONSTRAINT PARADA_PK PRIMARY KEY (PERCURSO, CODIGO),
	CONSTRAINT PARADA_FK1 FOREIGN KEY (PERCURSO) REFERENCES PERCURSO(NOME)
);

CREATE TABLE ADMINISTRADOR (
	USUARIO VARCHAR(128) NOT NULL,
	SENHA VARCHAR(128) NOT NULL,
	CONSTRAINT ADMINISTRADOR_PK PRIMARY KEY (USUARIO)
);
